const MAX_WIDTH = 1200;
const MIN_WIDTH = 345;

const POST_MAX_WIDTH = 700;
const DRAWER_WIDTH = 215;

const IMG_WIDTH = 92;
const IMG_HEIGHT = 92;

const NAV_HEIGHT = 60;
const FOOTER_HEIGHT = 150;
const HEADER_COVER_IMG_HEIGHT = 300;
const HEADER_HEIGHT = 140;

const PADDING = 30;
const PAGE_PADDING_BOTTOM = 100;

const COUNT_PER_PAGE = 6;
const COUNT_PER_CAROUSEL = 5;

const THEME_VALUE = 'light';

export {DRAWER_WIDTH,PAGE_PADDING_BOTTOM, FOOTER_HEIGHT, COUNT_PER_CAROUSEL, PADDING, MAX_WIDTH,HEADER_COVER_IMG_HEIGHT, NAV_HEIGHT, POST_MAX_WIDTH, THEME_VALUE, MIN_WIDTH, COUNT_PER_PAGE, HEADER_HEIGHT, IMG_HEIGHT, IMG_WIDTH};