const MAX_WIDTH = 1200;
const MIN_WIDTH = 345;

const POST_MAX_WIDTH = 700;
const DRAWER_WIDTH = 210;

const NAV_HEIGHT = 64;
const HEADER_HEIGHT = 140;

const COUNT_PER_PAGE = 10;

const THEME_VALUE = 'light';

export {DRAWER_WIDTH, MAX_WIDTH, NAV_HEIGHT, POST_MAX_WIDTH, THEME_VALUE, MIN_WIDTH, COUNT_PER_PAGE, HEADER_HEIGHT};